# Tokyo Night Light

[colors.primary]
background = "#E1E2E7"
foreground = "#3760BF"

[colors.cursor]
cursor = "#2E7DE9"
text = "#E1E2E7"

[colors.selection]
background = "#B7C1E3"
text = "#3760BF"

[colors.normal]
black = "#B4B5B9"
red = "#F52A65"
green = "#587539"
yellow = "#8C6C3E"
blue = "#2E7DE9"
magenta = "#9854F1"
cyan = "#007197"
white = "#6172B0"

[colors.bright]
black = "#A1A6C5"
red = "#F52A65"
green = "#587539"
yellow = "#8C6C3E"
blue = "#2E7DE9"
magenta = "#9854F1"
cyan = "#007197"
white = "#3760BF"
